INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 11, 'RO', 'RONDÔNIA' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 12, 'AC', 'ACRE' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 13, 'AM', 'AMAZONAS' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 14, 'RR', 'RORAIMA' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 15, 'PA', 'PARÁ' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 16, 'AP', 'AMAPÁ' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 17, 'TO', 'TOCANTINS' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 21, 'MA', 'MARANHÃO' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 22, 'PI', 'PIAUÍ' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 23, 'CE', 'CEARÁ' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 24, 'RN', 'RIO GRANDE DO NORTE' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 25, 'PB', 'PARAÍBA' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 26, 'PE', 'PERNAMBUCO' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 27, 'AL', 'ALAGOAS' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 28, 'SE', 'SERGIPE' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 29, 'BA', 'BAHIA' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 31, 'MG', 'MINAS GERAIS' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 32, 'ES', 'ESPÍRITO SANTO' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 33, 'RJ', 'RIO DE JANEIRO' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 35, 'SP', 'SÃO PAULO' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 41, 'PR', 'PARANÁ' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 42, 'SC', 'SANTA CATARINA' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 43, 'RS', 'RIO GRANDE DO SUL' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 50, 'MS', 'MATO GROSSO DO SUL' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 51, 'MT', 'MATO GROSSO' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 52, 'GO', 'GOIÁS' );
INSERT INTO tbl_estado ( cod_ibge, uf, nome ) VALUES ( 53, 'DF', 'DISTRITO FEDERAL' );